### ISSUE TITLE
toolbox-export, freaks out if there are folders in .local/share/applications

### ISSUE THREAD

**Issue by rosskarchner** [A6GibKm/silverblue-tools#3]
For instance, the one that wine creates
```
⬢[theross@toolbox silverblue-tools]$ ./toolbox-export com.usebottles.bottles
Traceback (most recent call last):
  File "/var/home/theross/projects/silverblue-tools/./toolbox-export", line 467, in <module>
    main()
  File "/var/home/theross/projects/silverblue-tools/./toolbox-export", line 455, in main
    copy_desktop_files(app, opts.container, desktop_files)
  File "/var/home/theross/projects/silverblue-tools/./toolbox-export", line 244, in copy_desktop_files
    copy_desktop_file(app, container, desktop_file)
  File "/var/home/theross/projects/silverblue-tools/./toolbox-export", line 276, in copy_desktop_file
    install(tmp_f.read(), new_path, resource)
  File "/var/home/theross/projects/silverblue-tools/./toolbox-export", line 120, in install
    if already_installed(new_data, resource):
  File "/var/home/theross/projects/silverblue-tools/./toolbox-export", line 99, in already_installed
    with open(f_path, "br") as data:
IsADirectoryError: [Errno 21] Is a directory: '/var/home/theross/.local/share/applications/wine'
```

**Comment by A6GibKm** [comment]
Thanks for the report, please test the latest commit and reopen if the issue persists.

**Comment by rosskarchner** [comment]
It worked! Thank you
